### ISSUE TITLE
Welcome login script

### ISSUE THREAD

**Issue by scorched-wow** [TheEpicLazyTaco/Basic-Scripts-For-Trinity-Core#1]
Hey, Login Script is not working at all..
Compiled is completed and ok
But login and try other account to log in and nothing happen.

Lastest core: https://github.com/TrinityCore/TrinityCore/pull/14865

**Comment by TheEpicLazyTaco** [comment]
Thanks ill look into this in the morning when i wake up Its prob a simple issue.

**Comment by TheEpicLazyTaco** [comment]
It works fine for me however it does seem to be very hard to see as its all white and there is a small issue with the string. Will fix it up and reupload it :palm_tree:

**Comment by TheEpicLazyTaco** [comment]
Thank you for your report however it did work. You might of just not noticed it. The message is sent right after the motd is. 

However by looking into this i realized it was very hard to see as it was white. 

I have updated the script. Try it again it worked fine for me.

**Comment by Ghostcrawler336** [comment]
awesome dude
